name: jaspr_ui
description: UI library for Jaspr.
by: Prince Bottoman(optiflowx)

version: 1.0.1
repository: https://github.com/optiflowx/jaspr_ui
publish_to: github

environment:
  sdk: '>=3.5.0 <5.0.0'

# Add regular dependencies here.
dependencies:
  jaspr: ^0.16.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
