name: jaspr_ui
description: UI library for Jaspr.
by: Prince Bottoman(optiflowx)
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.3.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  jaspr: ^0.13.3
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
